// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace src.Models
{
    public partial class Home
    {
        public const string Codename = "home";
        public const string CoreServicesCodename = "core_services";
        public const string PromotedArticleCodename = "promoted_article";
        public const string TeaserCodename = "teaser";
        public const string TitleCodename = "title";

        public IEnumerable<object> CoreServices { get; set; }
        public IEnumerable<object> PromotedArticle { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Teaser { get; set; }
        public string Title { get; set; }
    }
}