// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace src.Models
{
    public partial class ServiceOffering
    {
        public const string Codename = "service_offering";
        public const string ContentCodename = "content";
        public const string SlugCodename = "slug";
        public const string SummaryCodename = "summary";
        public const string ThumbnailCodename = "thumbnail";
        public const string TitleCodename = "title";

        public string Content { get; set; }
        public string Slug { get; set; }
        public string Summary { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<IAsset> Thumbnail { get; set; }
        public string Title { get; set; }
    }
}